// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropzoneController from "./dropzone_controller.js"
application.register("dropzone", DropzoneController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import SwiperController from "./swiper_controller"
application.register("swiper", SwiperController)

import CheckEmailController from "./check_email_controller"
application.register("check_email", CheckEmailController)

import GalleryController from "./gallery_react_controller.jsx"
application.register("gallery_react", GalleryController)